name: test workflow

on:
 push:
   branches:
     - main

env:
  CLEAR_ON_TEST_FAILURE: false
  CLEAR_RESOURCES: ture

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: apitest
        id: execution
        continue-on-error: true
        run: |
          exit 1
      - name: Error handling
        if: ${{ steps.execution.outcome == 'failure' }}
        run: |
          echo "CLEAR_RESOURCES=${{ env. CLEAR_ON_TEST_FAILURE }}" >> $GITHUB_ENV
          echo ${{ env.CLEAR_RESOURCES }}
          exit 1
  result:
    name: result
    runs-on: ubuntu-latest
    steps:
      - name: result
        run: echo ${{ env.CLEAR_RESOURCES }}

    
   



