name: test workflow

on:
 push:
   branches:
     - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - run: oc version



