name: test workflow

on:
 push:
   branches:
     - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
#      - uses: actions/checkout@v2
      - uses: ./.github/actions/checkout
      - run: ls -la
      - run: echo ok 



